name = "spinmacho-casino-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmacho-casino.pt"
HMAC_KEY = "39ece111fdb450eaaf2d42865a49423ea364e0d1704a71fb598e68aee93d20fb"
COOKIE_NAME = "1lt"
PLAY_PATH = "play-now"
BUTTON_ID = "p2ef6bbe1b2214d2f8ab238624eba2429"
GATE_SALT = "adee97347041f9f9"
